/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Build a Multimodal PDF Agent with n8n",
  "tagline": "Process, encode, and search PDFs using MongoDB Vector Search, Voyage AI, and n8n automation",
  "url": "https://multimodal-pdf-agent-n8n.github.io",
  "baseUrl": "/multimodal-pdf-agent-n8n/",
  "projectName": "mongodb-developer.github.io",
  "organizationName": "mongodb-developer",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.svg",
  "deploymentBranch": "gh-pages",
  "staticDirectories": [
    "static"
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "es"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "startButtonTitle": "Start Building",
    "featureList": [
      {
        "title": "Visual Workflow Building",
        "illustration": "img/n8n-workflow.png",
        "description": "\n        Build complex AI agents using n8n's visual interface - no coding required!\n    "
      },
      {
        "title": "Multimodal Processing",
        "illustration": "img/multimodal.png",
        "description": "\n        Process both text and images from PDFs using Voyage AI's multimodal embeddings.\n    "
      },
      {
        "title": "Production-Ready",
        "illustration": "img/mongodb-atlas.png",
        "description": "\n        Deploy scalable vector search with MongoDB Atlas and n8n's robust automation.\n    "
      }
    ],
    "utmParams": "utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=multimodal_pdf_agent_n8n&utm_term=michael.lynn"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/michael.lynn/code/ai4/workshop-docs/sidebars.js",
          "editUrl": "https://github.com/mongodb-developer/multimodal-pdf-agent-n8n/blob/main"
        },
        "theme": {
          "customCss": "/Users/michael.lynn/code/ai4/workshop-docs/src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-ZJ28V71VTQ",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    [
      "/Users/michael.lynn/code/ai4/workshop-docs/node_modules/docusaurus-lunr-search/src/index.js",
      {
        "languages": [
          "es",
          "en"
        ]
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "announcementBar": {
      "id": "feedback_form",
      "content": "This is a demonstration that we can put a pop-up message here! Even <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"#\">links</a>",
      "backgroundColor": "#fafbfc",
      "textColor": "#091E42",
      "isCloseable": true
    },
    "navbar": {
      "title": "Build a Multimodal PDF Agent with n8n",
      "logo": {
        "alt": "MongoDB Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg",
        "className": "navbar-logo",
        "width": "135px",
        "height": "100%"
      },
      "items": [
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "label": "Try MongoDB Atlas",
          "href": "https://www.mongodb.com/try?utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=multimodal_pdf_agent_n8n&utm_term=michael.lynn"
        },
        {
          "label": "Forums",
          "href": "https://www.mongodb.com/community/forums?utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=multimodal_pdf_agent_n8n&utm_term=michael.lynn"
        },
        {
          "label": "Developer Center",
          "href": "https://www.mongodb.com/developer?utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=multimodal_pdf_agent_n8n&utm_term=michael.lynn"
        },
        {
          "label": "MongoDB University",
          "href": "https://learn.mongodb.com?utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=multimodal_pdf_agent_n8n&utm_term=michael.lynn"
        },
        {
          "href": "https://github.com/mongodb-developer/multimodal-pdf-agent-n8n",
          "label": "Workshop GitHub (Deployment)"
        }
      ],
      "copyright": "© 2025 MongoDB, Inc."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "powershell",
        "swift",
        "kotlin"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "forest"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": true
    },
    "experimental_router": "browser"
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
